name: test-docker-build

on: [push]

jobs:
  build_docker_image:
    name: build_docker
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.dockerhub_user }}
        password: ${{ secrets.dockerhub_password }}
        dockerfile: docker/Dockerfile
        path: docker/
        repository: cschin/mater
        tags: latest
